name: Code linting using diff-cache and linters
run-name: Code linting
on: [push]
concurrency:
  group: ${{ github.ref }}-linting
  cancel-in-progress: true

jobs:
  check-changed-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Lint changed Markdown files
        uses: docker://avtodev/markdown-lint:v1
      - name: Lint all Ansible files
        uses: ansible/ansible-lint@main
        with:
          args: "--config-file=./.github/configs/ansible-lint.yaml $(find ansible/ -type f -name '*.yml' -o -name '*.yaml')"
